#!/usr/bin/env python

import os
import subprocess

user = os.getenv("SUDO_USER")

if (user == None):    #Checki if the user is SUDO
    print ("You need root to install this!")
    exit()

cwd = os.getcwd()
serviceFileTemplate = open("SenseHatMonitor.service.template", "r")

subprocess.call(["ln","-s",cwd+"SenseHatMonitor.py","/usr/local/bin/SenseHatMonitor"])
subprocess.call(["cp","SenseHatMonitor.service", "/lib/systemd/system/SenseHatMonitor.service"]) 
